name: unipy

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - smt
  - matplotlib
  - plotly
  - sphinx
  - sphinx_rtd_theme
  - pytest
  - black
  - ipykernel 

channels:
  - defaults
  - conda-forge